/* Generated by minidic */
module minidic.__package__;

static import md = minid.api;
static import mdu = minid.utils;
static import mdi = minidic.binding;

static import minidic.NativeArray;
struct MD_Module
{
static:
  void init(md.MDThread* t)
  {
    minidic.NativeArray.MD_Module.init(t);
    
    md.makeModule(t, "minidic", function md.uword(md.MDThread* t, md.uword numParams)
    {
      return 0;
    });
  }
}

